import { Profile, Hobby, Message } from './types';

export const POPULAR_HOBBY_NAMES = [
  'Music',
  'Gaming',
  'Cricket',
  'Football',
  'Gym',
  'Coding',
  'Dancing',
  'Movies',
  'Reading',
  'Travelling',
  'Cooking',
  'Photography',
  'Anime',
  'Content Creation',
  'Self Improvement',
  'Making New Friends',
];

export const INITIAL_HOBBIES: Hobby[] = [
  { id: 1, name: 'Music', category: 'Music & Audio', color: 'purple' },
  { id: 2, name: 'Bollywood', category: 'Music & Audio', color: 'coral' },
  { id: 3, name: 'Hip-Hop', category: 'Music & Audio', color: 'purple' },
  { id: 4, name: 'K-Pop', category: 'Music & Audio', color: 'coral' },
  { id: 5, name: 'Singing', category: 'Music & Audio', color: 'purple' },
  { id: 6, name: 'Gaming', category: 'Gaming', color: 'teal' },
  { id: 7, name: 'BGMI', category: 'Gaming', color: 'teal' },
  { id: 8, name: 'Free Fire', category: 'Gaming', color: 'coral' },
  { id: 9, name: 'Valorant', category: 'Gaming', color: 'purple' },
  { id: 10, name: 'Anime', category: 'Entertainment', color: 'coral' },
  { id: 11, name: 'Movies', category: 'Entertainment', color: 'purple' },
  { id: 12, name: 'Web Series', category: 'Entertainment', color: 'teal' },
  { id: 13, name: 'Cricket', category: 'Sports', color: 'teal' },
  { id: 14, name: 'Football', category: 'Sports', color: 'coral' },
  { id: 15, name: 'Badminton', category: 'Sports', color: 'purple' },
  { id: 16, name: 'Basketball', category: 'Sports', color: 'coral' },
  { id: 17, name: 'Gym', category: 'Fitness', color: 'coral' },
  { id: 18, name: 'Calisthenics', category: 'Fitness', color: 'teal' },
  { id: 19, name: 'Running', category: 'Fitness', color: 'purple' },
  { id: 20, name: 'Cycling', category: 'Fitness', color: 'teal' },
  { id: 21, name: 'Coding', category: 'Tech & Business', color: 'teal' },
  { id: 22, name: 'AI', category: 'Tech & Business', color: 'purple' },
  { id: 23, name: 'Startups', category: 'Tech & Business', color: 'teal' },
  { id: 24, name: 'Entrepreneurship', category: 'Tech & Business', color: 'coral' },
  { id: 25, name: 'Photography', category: 'Creative & Arts', color: 'teal' },
  { id: 26, name: 'Video Editing', category: 'Creative & Arts', color: 'purple' },
  { id: 27, name: 'Content Creation', category: 'Creative & Arts', color: 'coral' },
  { id: 28, name: 'Drawing', category: 'Creative & Arts', color: 'purple' },
  { id: 29, name: 'Dancing', category: 'Creative & Arts', color: 'coral' },
  { id: 30, name: 'Fashion', category: 'Creative & Arts', color: 'coral' },
  { id: 31, name: 'Reading', category: 'Lifestyle & Outdoors', color: 'teal' },
  { id: 32, name: 'Travelling', category: 'Lifestyle & Outdoors', color: 'teal' },
  { id: 33, name: 'Food', category: 'Lifestyle & Outdoors', color: 'coral' },
  { id: 34, name: 'Cooking', category: 'Lifestyle & Outdoors', color: 'coral' },
  { id: 35, name: 'Café Hopping', category: 'Lifestyle & Outdoors', color: 'purple' },
  { id: 36, name: 'Trekking', category: 'Lifestyle & Outdoors', color: 'teal' },
  { id: 37, name: 'Self Improvement', category: 'Mindset & Social', color: 'teal' },
  { id: 38, name: 'Psychology', category: 'Mindset & Social', color: 'purple' },
  { id: 39, name: 'Making New Friends', category: 'Mindset & Social', color: 'coral' },
  { id: 40, name: 'Deep Conversations', category: 'Mindset & Social', color: 'purple' },
];

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'usr_001',
    full_name: 'Aarav Sharma',
    department: 'Computer Science & Engg (UIET)',
    year: '3',
    gender: 'Male',
    college: 'CSJMU',
    email_verified: true,
    verification_status: 'verified',
    id_card_url: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    bio: 'Building web3 apps, jamming guitar on campus after midnight. Always ready for a hackathon squad!',
    is_admin: false,
    is_demo: true,
    created_at: '2026-08-01T10:00:00Z',
    email: 'aarav.cs22@example.com',
    hobbies: [
      { id: 3, name: 'Coding', color: 'teal' },
      { id: 2, name: 'Singing', color: 'purple' },
    ],
  },
  {
    id: 'usr_002',
    full_name: 'Priya Verma',
    department: 'Biotechnology',
    year: '2',
    gender: 'Female',
    college: 'CSJMU',
    email_verified: true,
    verification_status: 'verified',
    id_card_url: 'https://images.unsplash.com/photo-1589386417686-0d34b5903d23?w=600&auto=format&fit=crop&q=80',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    bio: 'Classical & contemporary dancer. Looking for dance crew members for the upcoming Spandan Fest!',
    is_admin: false,
    is_demo: true,
    created_at: '2026-08-05T14:30:00Z',
    email: 'priya.bio23@example.com',
    hobbies: [
      { id: 1, name: 'Dancing', color: 'coral' },
      { id: 4, name: 'Fitness', color: 'coral' },
    ],
  },
  {
    id: 'usr_003',
    full_name: 'Rohan Gupta',
    department: 'Mechanical Engineering',
    year: '4',
    gender: 'Male',
    college: 'CSJMU',
    email_verified: true,
    verification_status: 'verified',
    id_card_url: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    bio: "Marathon runner & gym rat. CSJMU sports ground 6 AM daily. Let's train together for inter-college trials.",
    is_admin: false,
    is_demo: true,
    created_at: '2026-08-10T09:15:00Z',
    email: 'rohan.me21@example.com',
    hobbies: [
      { id: 4, name: 'Fitness', color: 'coral' },
      { id: 5, name: 'Athletics', color: 'purple' },
    ],
  },
  {
    id: 'usr_004',
    full_name: 'Sneha Patel',
    department: 'Business Administration (MBA)',
    year: '1',
    gender: 'Female',
    college: 'CSJMU',
    email_verified: true,
    verification_status: 'pending',
    id_card_url: 'https://images.unsplash.com/photo-1589386417686-0d34b5903d23?w=600&auto=format&fit=crop&q=80',
    avatar_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&auto=format&fit=crop&q=80',
    bio: 'Product management enthusiast, singer, and badminton player. New to campus and exploring clubs!',
    is_admin: false,
    is_demo: true,
    created_at: '2026-08-15T11:20:00Z',
    email: 'sneha.mba24@example.com',
    hobbies: [
      { id: 2, name: 'Singing', color: 'purple' },
      { id: 5, name: 'Athletics', color: 'purple' },
    ],
  },
  {
    id: 'usr_005',
    full_name: 'Aditya Srivastava',
    department: 'Pharmacy (B.Pharm)',
    year: '2',
    gender: 'Male',
    college: 'CSJMU',
    email_verified: true,
    verification_status: 'unverified',
    id_card_url: null,
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    bio: 'Photographer and weekend trekker. Looking for folks to explore Kanpur street food & heritage.',
    is_admin: false,
    is_demo: true,
    created_at: '2026-08-20T16:45:00Z',
    email: 'aditya.pharm23@example.com',
    hobbies: [
      { id: 6, name: 'Other', color: 'teal' },
      { id: 4, name: 'Fitness', color: 'coral' },
    ],
  },
  {
    id: 'usr_006',
    full_name: 'Ananya Mishra',
    department: 'Mass Communication & Journalism',
    year: '3',
    gender: 'Female',
    college: 'CSJMU',
    email_verified: true,
    verification_status: 'verified',
    id_card_url: 'https://images.unsplash.com/photo-1589386417686-0d34b5903d23?w=600&auto=format&fit=crop&q=80',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    bio: 'Podcaster & stage theatre director. Need creative writers and voices for the campus newsletter.',
    is_admin: false,
    is_demo: true,
    created_at: '2026-08-22T08:00:00Z',
    email: 'ananya.mc22@example.com',
    hobbies: [
      { id: 2, name: 'Singing', color: 'purple' },
      { id: 1, name: 'Dancing', color: 'coral' },
      { id: 6, name: 'Other', color: 'teal' },
    ],
  },
];

export const INITIAL_MESSAGES: Message[] = [
  {
    id: 'msg_001',
    sender_id: 'usr_001',
    receiver_id: 'usr_002',
    content: 'Hey Priya! Saw you are into dance. Are you participating in the upcoming Spandan inter-college cultural night?',
    created_at: '2026-08-25T14:10:00Z',
  },
  {
    id: 'msg_002',
    sender_id: 'usr_002',
    receiver_id: 'usr_001',
    content: 'Hey Aarav! Yes, our group is putting together a fusion routine! Are you guys doing the acoustic band?',
    created_at: '2026-08-25T14:15:00Z',
  },
  {
    id: 'msg_003',
    sender_id: 'usr_001',
    receiver_id: 'usr_002',
    content: 'Yes! We are rehearsing at the OAT amphitheater tomorrow around 6 PM if you want to catch the vibe.',
    created_at: '2026-08-25T14:20:00Z',
  },
];
